kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: machine-operator-clusterrole
  uid: ba80734f-5025-4c58-bb50-e429a06c7f28
  resourceVersion: '129500895'
  creationTimestamp: '2025-01-23T17:42:04Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"machine-operator-clusterrole"},"rules":[{"apiGroups":["apiextensions.k8s.io"],"resources":["machines","machinesets"],"verbs":["get","list","watch","create","update","patch","delete"]}]}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2025-01-23T17:42:04Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
    - manager: Mozilla
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2025-01-24T09:27:51Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:rules': {}
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - apiextensions.k8s.io
      - machine.openshift.io
    resources:
      - machines
      - machinesets
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - pods
      - nodes
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
